apiVersion: apps/v1
kind: Deployment
metadata:
  name: client_deployment
  labels:
    app: clientfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientfrontend
  template:
    metadata:
      labels:
        app: clientfrontend
    spec:
      containers:
      - name: clientfrontend
        image: gcr.io/mwirabua/yolo_k8ip_client
        ports:
        - containerPort: 3000
        volumeMounts:
          - mountPath: /vol
            name: client-volume
      volumes:
        - name: client-volume
          # This GCE PD must already exist.
          gcePersistentDisk:
            pdName: my-data-disk
            fsType: ext4
      # envFrom:
      # - secretRef:
      #     name: SECRETS_NAME