apiVersion: v1
kind: Service
metadata:
  name: client_frontend
spec:
  selector:
    app: client_frontend 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5001 # External
    targetPort: 3000 # Container
    nodePort: 31110 # Node (Machine running the container)

    # kubectl apply -f service.yaml