apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend_deployment
  labels:
    app: backend_server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend_server
  template:
    metadata:
      labels:
        app: backend_server 
    spec:
      containers:
      - name: backend_server
        image: gcr.io/mwirabua/yolo_k8ip_backend
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: /vol
            name: backend-volume
      volumes:
        - name: backend-volume
          # This GCE PD must already exist.
          gcePersistentDisk:
            pdName: my-data-disk
            fsType: ext4
      # envFrom:
      # - secretRef:
      #     name: SECRETS_NAME
      # envFrom:
      # - secretRef:
      #     name: SECRETS_NAME
